name: Pronto
on: [pull_request]

jobs:
  pronto:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['4.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - run: |
          git fetch --no-tags --prune origin +refs/heads/*:refs/remotes/origin/*
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Pronto
        run: bundle exec pronto run -c origin/${{ github.base_ref }}
